version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
    image: redis:latest
    container_name: local-redis
    ports:
      - "6379:6379"